version: "3.9"  # optional since v1.27.0
services:
  tensorboard:
    image: tensorboard
    build:
      context: .
      dockerfile: Dockerfile.tensorboard
    container_name: tensorboard
    ports:
      - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
    volumes:
      - ${SAVE_DIR}:/save
    command:
      ["tensorboard",
      "--logdir=/save",
      "--port=${TENSORBOARD_PORT}",
      "--bind_all"]
  jupyterlab:
    image: jupyterlab:machine-learning
    build:
      context: .
      dockerfile: Dockerfile.jupyterlab
    container_name: jupyterlab
    ports:
      - ${JUPYTERLAB_PORT}:${JUPYTERLAB_PORT}
    volumes:
      - ${SAVE_DIR}:/save
    runtime: nvidia
    command:
      ["jupyter-lab",
      "--port=${JUPYTERLAB_PORT}",
      "--ip=0.0.0.0",
      "--allow-root",
      "--no-browser"]