version: "3.9"  # optional since v1.27.0
services:
  tensorboard:
    image: tensorboard
    build:
      context: .
      dockerfile: Dockerfile.tensorboard
    container_name: tensorboard
    ports:
      - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
    volumes:
      - ${SAVE_DIR}:/save
    command:
      ["tensorboard",
      "--logdir=/save",
      "--port=${TENSORBOARD_PORT}",
      "--bind_all"]
  jupyterlab:
    image: jupyterlab:machine-learning
    build:
      context: .
      dockerfile: Dockerfile.jupyterlab
    container_name: jupyterlab
    # device_requests:
    #   - capabilities:
    #     - "gpu"
    # env_file: .env
    ports:
      - ${JUPYTERLAB_PORT}:${JUPYTERLAB_PORT}
    volumes:
      - ${SAVE_DIR}:/save
    command:
      ["jupyterlab",
      "--port=${JUPYTERLAB_PORT}"]